R/gtfs_as_sf.R
Set the coordinate system for the correct `st_length` calculation
=> set coordinate system

R/gtfs2gps_dt_parallel.R
=> Handling closed circuits manually

R/gtfs2gps_single_dt.R, R/mod_updates.R, R/test_gtfs_freq.R
More explanation is found on #3
=> Merge `gtfs2gps_dt` scripts + minor adjustments

R/gtfs2gps_single_dt.R, R/read_gtfs.R, R/zzz.R, man/gtfs2gps_dt_single.Rd, src/snap_points.cpp, tests/testthat/test_gtfs2gps_dt_parallel.R, tests/testthat/test_gtfs2gps_dt_single.R, tests/testthat/test_read_gtfs.R, tests/testthat/test_snap_points.R, tests/testthat/test_write_gtfs.R
- Removing possible problem in `cpp_snap_points()` #33 
- When processing `gtfs2gps_single_dt()`, if the user set an output filepath, there will be no returning value in R, as everything will be stored into files. #35 (which might also be a solution to #31)
- 100% code coverage after removing `gtfs2gps_dt_parallel_freq.R` and `gtfs2gps_dt_parallel.R`. #32
=> more updates towards 1.0 version

R/gtfs2gps_single_dt.R, R/mod_updates.R, tests/testthat/test_gtfs2gps_dt_single.R, tests/testthat/test_read_gtfs.R
- Ignoring midnight trips #9
- Removing a small bug in the tests
- Other small improvements in the code
=> Small improvements

R/mod_updates.R
based on @pedro-andrade-inpe suggestion #46
=> simplification on mod_updates

R/gtfs2gps_single_dt.R
=> exclude condition based on GTFS data type

R/RcppExports.R, R/gtfs2gps.R, R/gtfs2gps_dt_parallel.R, R/gtfs2gps_dt_parallel_freq.R, man/cpp_snap_points.Rd, src/RcppExports.cpp, src/snap_points.cpp, tests/testthat/test_snap_points.R
This PR is related to issue #50 that @Joaobazzo  opened. It might help to track the error.
=> Showing trip_id when the maximum distance threshold is reached

DESCRIPTION, R/filter_day_period.R, R/gps_as_sf.R, R/gtfs2gps.R, R/mod_updates.R, man/filter_day_period.Rd, tests/testthat/test_gtfs2gps.R
=> fixing bugs

DESCRIPTION, R/gtfs2gps.R, R/mod_updates.R, src/snap_points.cpp, tests/testthat/test_gtfs2gps.R, vignettes/intro_to_gtfs2gps.Rmd
=> Updated version in CRAN - 1.0-7

R/filter_gtfs.R, R/gtfs2gps.R, R/read_gtfs.R, src/snap_points.cpp, tests/testthat/test_filter_gtfs.R, tests/testthat/test_gps_as_sflinestring.R, tests/testthat/test_read_gtfs.R, tests/testthat/test_snap_points.R, vignettes/intro_to_gtfs2gps.Rmd
- Allowing to read gtfs files without calendar/agency.
- Converting stop_ids to character.
- Stopping when shape_id has no stops.
- Stopping when no departure_time is found.
=> Version 1.2-1. Fixing small bugs and other small changes

R/gps_as_sflinestring.R
fix problems with unique trip_id's  `gps_as_sflinestring`
=> add info to fix #128

R/gtfs2gps.R, R/mod_updates.R
- Standardizing messages when tripids have problems with stop_ids
- Using tryCatch to avoid stopping gtfs2gps when there is an unknown error in some shapeid
=> improving user's feedbacks

DESCRIPTION, R/gps_as_sflinestring.R
Comparing times for Sao Paulo:
=> Speeding up conversion to sf_linestring

R/filter_day_period.R, R/mod_updates.R, R/write_gtfs.R, tests/testthat/test_gtfs2gps.R
=> Adding missing warning in trips without gps points

DESCRIPTION, R/filter_day_period.R, R/gtfs2gps.R, R/read_gtfs.R, tests/testthat/test_gtfs2gps.R
- Checking if agencies exist in filter by day period @Joaobazzo 
- Show the percentage of shapes and trips processed after converting to gps @Joaobazzo 
- Converting route_ids to character @ibarraespinosa
- Checking if frequencies data.table is not empty @ibarraespinosa
=> fixing small bugs

R/merge_gtfs_feeds.R, R/read_gtfs.R, tests/testthat/test_merge_gtfs_feeds.R
- Close #34
- Show messages for each file read in `read_gtfs()`
=> merge_gtfs_feeds + read_gtfs (messages)

R/gps_as_sflinestring.R, R/gtfs2gps.R, R/read_gtfs.R, man/gtfs2gps.Rd, src/distance_calcs.cpp, tests/testthat/test_gps_as_sflinestring.R, tests/testthat/test_gtfs2gps.R, tests_rafa/test_rafa.R
=> two updates

DESCRIPTION, R/filter_day_period.R, R/gps_as_sflinestring.R, R/gtfs2gps.R, R/merge_gtfs_feeds.R, R/mod_updates.R, R/read_gtfs.R, R/simplify_shapes.R, man/gtfs2gps.Rd, tests/testthat/test_gtfs2gps.R, tests/testthat/test_read_gtfs.R, tests_rafa/merge_gtfs_feeds.R
=> Version 1.3-2 to CRAN

.Rbuildignore, .Rprofile, DESCRIPTION, R/gps_as_sflinestring.R, R/gtfs2gps.R, R/merge_gtfs_feeds.R, R/mod_updates.R, R/zzz.R, tests/testthat/test_gtfs2gps.R
- Updates recommended by goodpractice package
- Close #43. Creating positive speeds for midnight trips
=> midnight trips

DESCRIPTION, NEWS.md
=> Updates for 1.4-0

R/gtfs2gps.R, R/mod_updates.R, R/zzz.R, tests/testthat/test_gtfs2gps.R
change way of writing trip_number
=> fix issue #189

tests/testthat/test_read_gtfs.R, tests/testthat/test_write_gtfs.R
This PR should also fix the errors found in #214
=> fixing routes after read_gtfs include short_name and long_name #212

README.md
This PR is an attempt to fix the README logo in the package website.
=> fixes logo on README

DESCRIPTION, NEWS.md, R/adjust_speed.R, R/append_height.R, R/gps_as_sfpoints.R, R/mod_updates.R, man/adjust_speed.Rd, man/append_height.Rd, man/gps_as_sfpoints.Rd, tests/testthat/test_adjust_speed.R, tests/testthat/test_append_height.R, tests/testthat/test_gtfs2gps.R
- Speeding up tests
- `cumtime` is now computed from `speed`
- removing last issues related to units
=> More changes to 2.0

DESCRIPTION, R/adjust_speed.R, man/adjust_speed.Rd, man/simplify_shapes.Rd
=> Small updates in the documentation

R/adjust_speed.R, R/gps_as_sflinestring.R, R/zzz.R, man/gps_as_sflinestring.Rd, tests/testthat/test_adjust_speed.R, tests/testthat/test_gps_as_sflinestring.R, tests_joao/issue249.R
bugs and improvements on adjust_speed and gps_as_sflinestring() functions
=> #249 and improvements

DESCRIPTION, tests/testthat/test_gtfs2gps.R
=> Updating tests for the newest version of units
